### PR TITLE
Add order_by and limit

### PR DESCRIPTION
**Pull request by FredrikNoren**

### CODE REVIEW

**Comment by FredrikNoren** [comment]
Sorry about the formatting, I have the editor to always do rustfmt on save. But maybe it would be good to just run `cargo fmt` on the whole project?

**Comment by jquesada2016** [comment]
@FredrikNoren thanks for the PR! If you can, please add a `rustfmt.toml` and run `cargo fmt` on the whole project. The reason it looks diferent is because I use weird default settings and never added the `rustfmt` config to the repo.

**Comment by FredrikNoren** [comment]
@jquesada2016 Done; I just added an empty rustfmt so that it's the default formatting

**Comment by jquesada2016** [comment]
@FredrikNoren thank you very much!

**Pull request merged**
