### PR TITLE
Misc improvments

### PR DESCRIPTION
**Pull request by FredrikNoren**
Figured I'd open a PR with the fixes I currently have on my fork (will probably be more, I'll just keep adding to this branch in that case).

### CODE REVIEW

**Comment by jquesada2016** [comment]
Hello! Thank you for opening this PR. Whenever you'd like me to review the PR for merging, just let me know!

**Comment by FredrikNoren** [comment]
@jquesada2016 I think you can review it as it is now; I'll probably have more fixes in the future but I can open new PRs for them then.

**Comment by jquesada2016** [comment]
@FredrikNoren just a heads up, I'm going to merge this in now, but I'm going to refactor the entire crate to use a new macro crate I made to help make declaring bindings with `wasm-bindgen` much less boiler-plate. Hopefully will be up in a few days.

**Comment by FredrikNoren** [comment]
@jquesada2016 Cool sounds good. Btw I also started working on a crate for rs to/from js object serialization. The normal serde thing doesn't work for Timestamps and other js native types that firebase expects in the structs. I'll put it up in a separate crate though

**Comment by jquesada2016** [comment]
@FredrikNoren sounds cool! But yeah, in general, working with `JsValue` and serde causes problems because there's no way to easily pass the data through to the other side of serde. I usually skip `JsValue`s and attach the objects after serialization.

**Comment by FredrikNoren** [comment]
@jquesada2016 Here it is: https://github.com/AmbientRun/Rs2Js

**Pull request merged**
