### PR TITLE
Expose more firestore functions

### PR DESCRIPTION
**Pull request by FredrikNoren**
update_doc, add_doc, from/to_millis etc.

### CODE REVIEW

**Comment by jquesada2016** [comment]
@FredrikNoren thank you for your continued help here. I'd like to give you an update. I haven't been using Firebase for a while. I've mostly been using `SurrealDB` and `EdgeDB`, which is why you haven't heard much from me on this repo. Would you like me to add you as a maintainer so you can push to `main`?

**Comment by FredrikNoren** [comment]
@jquesada2016 Sure yeah. Can you also add me to the crate on crates.io? And would it be ok if I moved the repo to https://github.com/ambientrun ?

**Comment by jquesada2016** [comment]
@FredrikNoren I'm going to merge this in now, so I can quickly fix this crate building on nightly.

**Comment by jquesada2016** [comment]
> @jquesada2016 Sure yeah. Can you also add me to the crate on crates.io? And would it be ok if I moved the repo to https://github.com/ambientrun ?

@FredrikNoren Sorry! I didn't see your reply. I'd be okay with moving the crate over to Ambient, but not with giving full access to the `crates.io` crate, because I'd like to make sure changes are verified before going up. You can ping me whenever you would like me to publish a new version, and I'll happily do so quickly.

How does that sound?

**Comment by FredrikNoren** [comment]
@jquesada2016 Ah ok, I figured you wanted to transition out of maintaining it, but if you're planing to keep push to crates.io etc. I think it makes sense to keep it here.

**Comment by jquesada2016** [comment]
@FredrikNoren are you still interested in taking over this repo and on crates.io? I've come to the conclusion that I will no longer be maintaining this crate, as I've moved all my projects out from using Google services.

**Comment by FredrikNoren** [comment]
@jquesada2016 Sure, we'll keep using it so might as well take over it

**Pull request merged**
